function yuvShow(filename)
% yuvShow()
% yuvShow(filename)
%
% Reads and displays a .yuv image generated by devCam. If no filename is
% supplied, prompts user to select a YUV file (or files).
%
% Rob Sumner,  March 2015


% Parse the input, one file or many?
if nargin==1
    % If a filename was actually passed
    process(filename)
else
    [fn fp] = uigetfile('*.yuv','Multiselect','on');
    
    if ischar(fn)
        % A single YUV image was selected
        filename = [fp fn];
        process(filename);
    else
        % Multiple YUV images were selected
        for i=1:length(fn)
            filename = [fp fn{i}];
            process(filename)
        end
    end
end

% This actually does the processing of the parsed input
    function process(filename)
        % Read in the image plane data from the file.
        [y, u, v] = yuvRead(filename);
        
        % The Y plane is twice the size of the U, V planes due to subsampling. It's
        % a little rudimentary, but MATLAB's built-in imresize works acceptably.
        % Stack the planes in the right way so we can convert to RGB.
        YUV = cat(3,y,...
            imresize(u,2),...
            imresize(v,2));
        
        % This is the right function for the color space that YUV_420_888 uses.
        RGB = ycbcr2rgb(YUV/256);
        
        figure
        imshow(RGB);
    end

end